name: Feature Request
description: Suggest a new feature or enhancement for KernelPyTorch
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please provide as much context as possible.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is it related to a frustration?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: textarea
    id: code-example
    attributes:
      label: Example Usage
      description: How would you use this feature? Provide code examples if applicable.
      render: python
      placeholder: |
        import kernel_pytorch as kpt

        # How you'd like to use the feature
        result = kpt.new_feature(...)

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - Attention (FlashAttention, MultiHead)
        - Precision (FP16, BF16, FP8)
        - Memory (Checkpointing, Optimizer States)
        - Hardware Backend (NVIDIA, AMD, Intel, TPU)
        - Distributed Training
        - Model Export
        - Deployment/Serving
        - MoE (Mixture of Experts)
        - CLI Tools
        - Configuration
        - Documentation
        - New Component
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to your workflow?
      options:
        - Nice to have
        - Would significantly improve my workflow
        - Critical for my use case
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      options:
        - label: I would be willing to contribute this feature
          required: false
        - label: I have searched existing issues to ensure this is not a duplicate
          required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or references about the feature request.
