#!/usr/bin/env python3
"""
Check version consistency across TorchBridge project files.

Two-phase check:
1. Verify pyproject.toml and CHANGELOG.md agree on the canonical version.
2. Scan ALL tracked files for hardcoded version strings that should be
   dynamically derived instead.  This prevents version drift when new
   files are added.
"""

import re
import subprocess
import sys
from pathlib import Path

# --- Phase 1: Canonical version consistency ---

CRITICAL_VERSION_FILES = {
    'pyproject.toml': r'version\s*=\s*"(\d+\.\d+\.\d+)"',
    'CHANGELOG.md': r'## \[(\d+\.\d+\.\d+)\]',
}

# --- Phase 2: Hardcoded version detection ---

# Files that are ALLOWED to contain the literal version string.
# Everything else must derive the version dynamically.
ALLOWED_VERSION_FILES = {
    'pyproject.toml',       # Source of truth
    'CHANGELOG.md',         # Release notes (every past version listed)
    'PKG-INFO',             # Auto-generated by setuptools
}

# Directories to skip entirely (not tracked / not relevant)
SKIP_DIRS = {'.git', '__pycache__', '.eggs', '*.egg-info', 'node_modules'}

# File extensions to scan (text files only)
SCAN_EXTENSIONS = {
    '.py', '.toml', '.cfg', '.ini', '.yaml', '.yml',
    '.md', '.rst', '.txt', '.sh', '.bash',
    '.dockerfile', '',  # Dockerfiles have no extension sometimes
}


def extract_version(file_path: Path, pattern: str) -> str | None:
    """Extract version from file using regex pattern."""
    try:
        content = file_path.read_text()
        match = re.search(pattern, content)
        if match:
            return match.group(1)
    except Exception as e:
        print(f"  Warning: Could not read {file_path}: {e}")
    return None


def get_tracked_files(project_root: Path) -> list[str]:
    """Get all git-tracked files plus any staged new files."""
    files: set[str] = set()
    try:
        # Already-tracked files
        result = subprocess.run(
            ['git', 'ls-files'],
            capture_output=True, text=True, check=True,
            cwd=project_root,
        )
        files.update(result.stdout.strip().splitlines())

        # Staged but not yet tracked (new files being committed)
        result = subprocess.run(
            ['git', 'diff', '--cached', '--name-only', '--diff-filter=A'],
            capture_output=True, text=True, check=True,
            cwd=project_root,
        )
        files.update(result.stdout.strip().splitlines())
    except Exception:
        pass
    return sorted(files)


def scan_for_hardcoded_version(
    project_root: Path, version: str,
) -> list[tuple[str, int, str]]:
    """
    Scan tracked files for hardcoded version strings.

    Returns list of (file_path, line_number, line_content) tuples.
    """
    hits = []

    # Patterns that indicate a hardcoded version (not just a mention in docs).
    # We look for the version in contexts like: version="X.Y.Z", "vX.Y.Z",
    # version: X.Y.Z, __version__ = "X.Y.Z", LABEL version=X.Y.Z
    hardcoded_patterns = [
        # Python: __version__ = "X.Y.Z" or version = "X.Y.Z"
        re.compile(rf'''version\s*=\s*["']{re.escape(version)}["']'''),
        # Docker LABEL: version="X.Y.Z" or image.version="X.Y.Z"
        re.compile(rf'''version=["']?{re.escape(version)}'''),
        # YAML: version: X.Y.Z or version: "X.Y.Z"
        re.compile(rf'''version:\s*["']?{re.escape(version)}["']?'''),
        # release = "X.Y.Z" (Sphinx conf.py style)
        re.compile(rf'''release\s*=\s*["']{re.escape(version)}["']'''),
    ]

    for rel_path in get_tracked_files(project_root):
        # Skip allowed files
        if rel_path in ALLOWED_VERSION_FILES:
            continue

        # Skip directories
        if any(skip in rel_path for skip in SKIP_DIRS):
            continue

        file_path = project_root / rel_path
        if not file_path.is_file():
            continue

        # Check extension (Dockerfiles have names like "Dockerfile.nvidia")
        suffix = file_path.suffix.lower()
        name = file_path.name.lower()
        is_dockerfile = name.startswith('dockerfile')
        if suffix not in SCAN_EXTENSIONS and not is_dockerfile:
            continue

        try:
            lines = file_path.read_text().splitlines()
        except (UnicodeDecodeError, OSError):
            continue

        for i, line in enumerate(lines, 1):
            for pattern in hardcoded_patterns:
                if pattern.search(line):
                    hits.append((rel_path, i, line.strip()))
                    break  # One hit per line is enough

    return hits


def main() -> int:
    """Check version consistency across all files."""
    project_root = Path(__file__).resolve().parent.parent.parent
    exit_code = 0

    # ── Phase 1: Critical file consistency ──────────────────────────
    print("Phase 1: Checking canonical version consistency...\n")

    critical_versions = {}
    for file_rel_path, pattern in CRITICAL_VERSION_FILES.items():
        file_path = project_root / file_rel_path
        ver = extract_version(file_path, pattern)
        if ver:
            critical_versions[file_rel_path] = ver
            print(f"   {file_rel_path}: v{ver}")
        else:
            print(f"   {file_rel_path}: NOT FOUND")
            exit_code = 1

    unique_critical = set(critical_versions.values())
    if len(unique_critical) > 1:
        print("\n  CRITICAL: Version mismatch!")
        for ver in sorted(unique_critical):
            files = [f for f, v in critical_versions.items() if v == ver]
            print(f"   v{ver}: {', '.join(files)}")
        exit_code = 1
    elif len(unique_critical) == 1:
        canonical_version = next(iter(unique_critical))
        print(f"\n  Phase 1 passed: v{canonical_version}")
    else:
        print("\n  No versions found in critical files!")
        return 1

    # ── Phase 2: Hardcoded version scan ─────────────────────────────
    print(f"\nPhase 2: Scanning for hardcoded '{canonical_version}' in tracked files...\n")

    hits = scan_for_hardcoded_version(project_root, canonical_version)

    if hits:
        print(f"  DRIFT DETECTED: {len(hits)} file(s) contain hardcoded version:\n")
        for rel_path, line_no, content in hits:
            print(f"   {rel_path}:{line_no}")
            print(f"      {content}\n")
        print("  FIX: Replace hardcoded versions with dynamic resolution.")
        print("  See scripts/ci/docker_build.sh and docs/conf.py for patterns.")
        exit_code = 1
    else:
        print("  Phase 2 passed: no hardcoded versions found")

    # ── Summary ─────────────────────────────────────────────────────
    if exit_code == 0:
        print(f"\nVersion check passed: v{canonical_version}")
    else:
        print("\nVersion check FAILED. Fix issues above before committing.")

    return exit_code


if __name__ == "__main__":
    sys.exit(main())
